name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  get-php-version:
    name: Get PHP Version
    runs-on: ubuntu-latest

    steps:
      - name: Check PHP Version
        id: php-version
        run: echo "::set-output name=php_version::$(php -r 'echo PHP_VERSION_ID;')"

  auto-review:
    name: Auto review
    needs: get-php-version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ ${ { needs.get-php-version.outputs.php_version } } ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Run phpcs
        run: composer phpcs

      - name: Run phpmd
        run: composer phpmd

  tests:
    name: Tests
    needs: get-php-version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ ${ { needs.get-php-version.outputs.php_version } } ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Run unit tests
        env:
          XDEBUG_MODE: coverage
        run: composer test

      - name: Run mutation tests
        run: composer test-mutation
